name: run tests

on:
  push:
    branches:
      - '*'  # Déclenche le workflow sur chaque push, peu importe la branche

jobs:
  test:
    runs-on: ubuntu-latest  # Le job s'exécute sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository  # Étape pour vérifier les fichiers du dépôt
        uses: actions/checkout@v4  # Utilise l'action checkout pour obtenir le code source

      - name: Set up Java 17  # Configure l'environnement Java 17 (ajuster selon la version nécessaire)
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Spécifie la version de Java à utiliser
          distribution: 'oracle'

      - name: Install Maven  # Installe Maven (ou Gradle si nécessaire)
        run: sudo apt-get install -y maven  # Utilise apt-get pour installer Maven

      - name: Install dependencies  # Installe les dépendances du projet
        run: mvn install  # execute et installe les tests de dépendances de maven

      - name: Run unit tests  # Exécute les tests unitaires
        run: mvn test  # execute et lance les tests de maven
